# Generated by Django 5.0.2 on 2024-03-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
